services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        value: 'django-insecure-x#@#m^-kjqjy-3)h-vpd^!-1!4950!nh5cbt+krd#281+komvc'
      - key: ALLOWED_HOSTS
        value: 'django-backend.onrender.com'
