# Generated by Django 5.1.6 on 2025-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categorie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
