# Generated by Django 5.1.6 on 2025-07-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fournisseur_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur_principal',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_achat',
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='inventory.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
